site_name: DATA::REGISTRY documentation
repo_url: https://github.com/vladislavmarkov/data_registry
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

plugins:
  - search
  - mike

nav:
  - Home: index.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - data_registry.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
  - data_registry.css

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search
  - mkdocstrings:
      default_handler: cxx

extra:
  version:
    provider: mike
  generator: false
