site_name: data::registry documentation

repo_url: https://github.com/vladislavmarkov/data_registry

docs_dir: docs

theme:
  name: mkdocs
  color_mode: auto
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  user_color_mode_toggle: true
  nav_style: dark

plugins:
  - search
  - mike
  - mkdocstrings:
      default_handler: cxx

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  version:
    provider: mike
  generator: false
