name: formatting

on: [push, pull_request]

permissions:
  contents: read

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: install cmake-format (cmakelang)
      run: |
        pip install --quiet cmakelang
        wget https://apt.llvm.org/llvm.sh
        sudo bash ./llvm.sh 19
        sudo apt install clang-format-19

    - uses: cachix/install-nix-action@v31
    - name: run treefmt in check mode
      run: nix shell nixpkgs#treefmt -c treefmt --ci
